### ISSUE TITLE
It seems there is a file named "parma2" missing

### ISSUE THREAD

**Issue by mrayur** [Zhaofeng-Tian/Adaptive-Cruise-Control-System-Modelling#1]
The error is shown as below, 
![image](https://user-images.githubusercontent.com/52965479/236594430-5418b1fd-e229-4647-a2eb-181f11d02846.png)

Looking forward to your reply whenever it is convenient for you.

**Comment by Zhaofeng-Tian** [comment]
Hi there,

This repo is not maintained right now. But I have uploaded the file, you can try it. The final results are not guaranteed, and the repo condition is as-is.
